# Shared analysis options for the entire GoPlus project
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/firebase_options.dart"

  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Adicionales a flutter_lints
    - always_declare_return_types
    - avoid_print
    - constant_identifier_names
    - directives_ordering
    - prefer_single_quotes
    - unnecessary_brace_in_string_interps
    - use_key_in_widget_constructors
