// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8QQnqJ_qQ_0QQnqJ_qQ_0QQnqJ_qQ_0',
    appId: '1:123456789:web:0123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'goplus-system-d647e',
    authDomain: 'goplus-system-d647e.firebaseapp.com',
    storageBucket: 'goplus-system-d647e.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8QQnqJ_qQ_0QQnqJ_qQ_0QQnqJ_qQ_0',
    appId: '1:123456789:android:0123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'goplus-system-d647e',
    storageBucket: 'goplus-system-d647e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8QQnqJ_qQ_0QQnqJ_qQ_0QQnqJ_qQ_0',
    appId: '1:123456789:ios:0123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'goplus-system-d647e',
    storageBucket: 'goplus-system-d647e.appspot.com',
    iosBundleId: 'com.goplus.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8QQnqJ_qQ_0QQnqJ_qQ_0QQnqJ_qQ_0',
    appId: '1:123456789:ios:0123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'goplus-system-d647e',
    storageBucket: 'goplus-system-d647e.appspot.com',
    iosBundleId: 'com.goplus.customerApp',
  );
}